package hr.dvasadva.media.nodes;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.InputStream;
import java.util.*;

/**
 * Use this component to load git.properties file, 
 * generated by the Maven Git plugin when building the project.
 */
public class GitProperties {

    private static final Logger log = LoggerFactory.getLogger(GitProperties.class);

    private final static String DEFAULT_GIT_PROPERTIES_FILENAME = "git.properties";

    public GitProperties() {

    }

    /**
     * Read all the <i>git.properties</i> as one {@link List} with {@link AbstractMap.SimpleEntry} items.
     * Note that this method will try to use the file found in class path.
     *
     * @return  git properties
     */
    public Properties read() {

        return this.read0(DEFAULT_GIT_PROPERTIES_FILENAME);
    }

    /**
     * Read all the <i>git.properties</i>, as one {@link List} with {@link AbstractMap.SimpleEntry} items.
     *
     * @param  fileName     use external file that contains git build information
     *
     * @return  git properties
     */
    public Properties read(final String fileName) {

        return this.read0(DEFAULT_GIT_PROPERTIES_FILENAME);
    }

    /**
     * Read the git.properties file from the class path.
     *
     * @param gitPropertiesFilename     name of the class path resources file, usually {@link #DEFAULT_GIT_PROPERTIES_FILENAME}
     *
     * @return  {@link Properties} of key,value entries
     */
    private Properties read0(final String gitPropertiesFilename)  {

        Properties prop = new Properties();
        
        try {

            final String resourceFile = gitPropertiesFilename;

            final ClassLoader classLoader = GitProperties.class.getClassLoader();
            final InputStream inputStream = classLoader.getResourceAsStream(resourceFile);

            prop.load(inputStream);
            
            return prop;
        }
        catch (final Exception ex) {

            log.error(String.format("Unable to read the input git properties file: %s. Check that it is available on the class path.", gitPropertiesFilename), ex);
        }

        return prop;
    }

}
